apiVersion: v1
kind: ConfigMap
metadata:
  name: ratemyubprof-configmap
  namespace: default  
data:
  config.json: |
    {
      "database": {
        "host": "localhost",
        "port": 5432,
        "user": "postgres",
        "password": "postgres",
        "name": "ratemyubprof",
        "sslmode": "disable"
      },
      "app": {
        "port": 80,
        "version": "1.0.0",
        "name": "ratemyubprof",
        "env": "development"
      },
      "logger": {
        "type": "development"
      },
      "jwt": {
        "atSecretKey": "",
        "atExpiredTime": 0,
        "rtSecretKey": "",
        "rtExpiredTime": 0
      }
    }
