apiVersion: v1
kind: ConfigMap
metadata:
  name: ratemyubprof-configmap
  namespace: default  
data:
  env.json: |
    {
      "database": {
        "host": "localhost",
        "port": 5432,
        "user": "postgres",
        "password": "postgres",
        "name": "ratemyubprof",
        "sslmode": "disable"
      },
      "app": {
        "port": 8000,
        "version": "1.0.0",
        "name": "ratemyubprof",
        "env": "production"
      },
      "logger": {
        "type": "production"
      },
      "jwt": {
        "atSecretKey": "aTsecretKey",
        "atExpiredTime": 1,
        "rtSecretKey": "rTsecretKey",
        "rtExpiredTime": 24
      }
    }
