apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratemyubprof-app-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: ratemyubprof-be
  template:
    metadata:
      labels:
        app: ratemyubprof-be
    spec:
      imagePullSecrets:
      - name: docker-registry-secret
      containers:
      - name: ratemyubprof-be
        image: dvnnfrr/ratemyubprof
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        volumeMounts:
          - name: config-volume
            mountPath: /app
            readOnly: true 
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: ratemyubprof-configmap
