apiVersion: v1
kind: ConfigMap
metadata:
  name: ratemyubprof-configmap
  namespace: default  
data:
  env.json: |
    {
      "database": {
        "host": "localhost",
        "port": 5432,
        "user": "postgres",
        "password": "postgres",
        "name": "ratemyubprof",
        "sslmode": "disable"
      },
      "app": {
        "port": 8000,
        "version": "1.0.0",
        "name": "ratemyubprof",
        "env": "production"
      },
      "logger": {
        "type": "production"
      },
      "jwt": {
        "atSecretKey": "aTsecretKey",
        "atExpiredTime": 1,
        "rtSecretKey": "rTsecretKey",
        "rtExpiredTime": 24
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratemyubprof-app-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: ratemyubprof-be
  template:
    metadata:
      labels:
        app: ratemyubprof-be
    spec:
      imagePullSecrets:
      - name: docker-registry-secret
      containers:
      - name: ratemyubprof-be
        image: dvnnfrr/ratemyubprof
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        volumeMounts:
          - name: config-volume
            mountPath: /app
            readOnly: true 
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: ratemyubprof-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: ratemyubprof-app-service
spec:
  selector:
    app: ratemyubprof-be
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
