apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-configmap
  namespace: default
data:
  rabbitmq.conf: |
    listeners.tcp.default = 5672
    default_user = guest
    default_pass = guest
    channel_max = 128
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: rabbitmq-deployment
  namesapce: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-deployment
  template:
    metadata:
      labels:
        app: rabbitmq-deployment
    spec: 
      containers:
        - name: rabbitmq 
          image: rabbitmq:4.0-management
          imagePullPolicy: Always
          resources:
            requests: 
              memory: "256Mi"
              cpu: "256m"
            limits:
              memory: "512Mi"
              cpu: "512m"
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - name: rabbitmq-config-volume
              mountPath: /etc/rabbitmq/rabbitmq.conf
              subPath: rabbitmq.conf 
      volumes:
        - name: rabbitmq-config-volume
          configMap:
            name: rabbitmq-configmap
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: rabbitmq-service
  namespace: default 
spec: 
  selector: 
    app: rabbitmq-deployment
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
  type: ClusterIP 
