volumes:
  postgres-data:

networks:
  rmbupworkspace:

services:
  workspace:
    container_name: rmubp-devcontainer-workspace
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
        # Ensure that the variables in .env match the same variables in devcontainer.json
        - .env

    volumes:
      - ../..:/workspaces:cached
    
    dns:
      - 127.0.0.11
      - 8.8.8.8
      - 1.1.1.1
      
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    networks:
      - rmbupworkspace

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    depends_on:
      - db 
      - rabbitmq

  db:
    container_name: rmubp-devcontainer-db
    image: postgres:16.1
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - .env
    networks:
      - rmbupworkspace

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rmubp-devcontainer-rabbitmq
    restart: unless-stopped
    networks:
      - rmbupworkspace